  @SpringBootApplication
    @EnableEurekaServer
    public class MsRegistryServerApplication {
    
    public static void main(String[] args) {
    SpringApplication.run(MsRegistryServerApplication.class, args);
    }
  
  }
